---

- hosts: default
  sudo: yes
  tasks:
    - name: Install packages
      apt: pkg={{ item }} state=latest update-cache=yes
      with_items:
        - build-essential
        - ruby1.9.3
        - rdiff-backup

    - name: Install gems
      gem: name={{ item }} state=latest user_install=no
      with_items:
        - rake
        - bundler

    - name: Install understudy
      gem: name=understudy state=present user_install=no gem_source=/understudy/pkg/understudy-0.0.11.gem
